name: sono_query
description: "Audio file discovery and metadata reading for Sono."

version: 0.5.0
homepage: https://github.com/appsono/sono_query

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  audio_metadata_reader: ^1.6.0
  plugin_platform_interface: ^2.1.8
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0

flutter:
  plugin:
    platforms:
      android:
        package: wtf.sono.packages.query
        pluginClass: SonoQueryPlugin
      ios:
        pluginClass: SonoQueryPlugin
      linux:
        dartPluginClass: SonoQueryDesktop
      windows:
        dartPluginClass: SonoQueryDesktop
